### DISCUSSION TITLE
v3.65.0 broken in GitHub Actions (shivammathur/setup-php)

### DISCUSSION THREAD

**Discussion by garyburgmann** [PHP-CS-Fixer/PHP-CS-Fixer#8304] [Q&A]
<img width="942" alt="image" src="https://github.com/user-attachments/assets/13fa979e-ada7-45f5-af00-4ead17cc21b6">

<img width="459" alt="image" src="https://github.com/user-attachments/assets/e3210072-cbd4-4295-8154-9965f20a8eda">

just pin to previous version fixed it for us

```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          ...
          tools: ..., php-cs-fixer:3.64.0
```
