### ISSUE TITLE
Error with multiple files check

### ISSUE THREAD

**Issue by V4lou** [PHP-CS-Fixer/PHP-CS-Fixer#7140]
### Description

Hello everyone.

I use php-cs-fixer with Grumphp in a vanilla PHP project (without any framework).

When I launch the task with php-cs-fixer  with a single commit PHP file I have no error in the CLI and I can fix the file if I have a problem with the syntax. 

But, when I launch the task with multiple files, I have this error:

```
In ConfigurationResolver.php line 561:
                                                                          
  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]  
  For multiple paths config parameter is required.                        
                                                                          

Exception trace:
  at /home/valentin/Projets/RolePlayGuard/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php:561
 PhpCsFixer\Console\ConfigurationResolver->computeConfigFiles() at /home/valentin/Projets/RolePlayGuard/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php:249
 PhpCsFixer\Console\ConfigurationResolver->getConfig() at /home/valentin/Projets/RolePlayGuard/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php:281
 PhpCsFixer\Console\ConfigurationResolver->getConfigFile() at /home/valentin/Projets/RolePlayGuard/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:260
 PhpCsFixer\Console\Command\FixCommand->execute() at /home/valentin/Projets/RolePlayGuard/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /home/valentin/Projets/RolePlayGuard/vendor/symfony/console/Application.php:1063
 Symfony\Component\Console\Application->doRunCommand() at /home/valentin/Projets/RolePlayGuard/vendor/symfony/console/Application.php:320
 Symfony\Component\Console\Application->doRun() at /home/valentin/Projets/RolePlayGuard/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:90
 PhpCsFixer\Console\Application->doRun() at /home/valentin/Projets/RolePlayGuard/vendor/symfony/console/Application.php:174
 Symfony\Component\Console\Application->run() at /home/valentin/Projets/RolePlayGuard/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:102
 include() at /home/valentin/Projets/RolePlayGuard/vendor/bin/php-cs-fixer:120

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]

You can fix errors by running the following command:
'/home/valentin/Projets/RolePlayGuard/vendor/bin/php-cs-fixer' '--using-cache=yes' '--path-mode=intersection' '--verbose' 'fix' 'account-connect-process.php' 'create-account.php' 'header.php' 'index.php'
```

The manual correction of the files with the extension in VSCode don't  fix the problem. I have the same message in the CLI.
 
Have you a trick to fix this error ? Or this is a bug ?

Thanks a lot for your responses.
Cordially

### Runtime version

Version of PHP: 8.2.8

Version of Php-cs-fixer: 3.21.1

### Configuration file

 I use this configuration in my grumphp.yml :  

```
grumphp:
    tasks:
        phplint: ~
        phpcsfixer2: 
           
                    allow_risky: ~
                    config: ~
                    triggered_by: ['php']
                    using_cache: true
                    cache_file: ~
                    config_contains_finder: true
                    verbose: true
                    rules: []

```
