### ISSUE TITLE
nullable union type wrongly changed

### ISSUE THREAD

**Issue by staabm** [PHP-CS-Fixer/PHP-CS-Fixer#7482]
### Description

we have a function which has a return type as follows

```
  /**
     * @return array{clxArtikel|null, \clxTarif|null}
     */
    private static function selectArticleTarif(LeistungsobjektTW $leistungsobjekt): array 
{}
```

the phpdoc is changed to 
`* @return array{(clxArtikel|null), (c(clxTarif|null)`

by one of these rules.

```
 * PhpCsFixer\Fixer\Import\OrderedImportsFixer
 * PhpCsFixer\Fixer\Phpdoc\PhpdocTypesOrderFixer
 ```

as a workaround I am using `* @return array{?clxArtikel, ?\clxTarif}` which works fine

![grafik](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/120441/4867f028-ba55-4d16-aea1-4677df96589d)

### Runtime version

```
Run shivammathur/setup-php@v2
  with:
    php-version: 7.4.15
    coverage: none
    extensions: gmp, soap 
```
